sudo: required
services:
    - docker
before_install:
    - docker build -t deshneil/react-app -f Dockerfile.dev .

script:
    - docker run -e CI=true deshneil/react-app npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "react-docker"
    env: "React"
    bucket_name: "elasticbeanstalk-us-west-2-163767414714"
    bucket_path: "React"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY